name: app
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '15'
            - run: npm ci
            - run: npm run build
              env:
                  REACT_APP_FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
                  REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
                  REACT_APP_FIREBASE_SENDER_ID: ${{ secrets.FIREBASE_SENDER_ID }}
                  REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
                  REACT_APP_FIREBASE_REGION: ${{ secrets.FIREBASE_REGION }}
